kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:14
    commands:
      - npm install
      - npm run build

  - name: test
    image: node:14
    commands:
      - npm install
      - npm test

  - name: publish
    image: plugins/docker
    settings:
      repo: thapapath/cicd-pipeline
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest

trigger:
  branch:
    - master
    - main

services:
  - name: docker
    image: docker:dind
