replicaCount: 1

image:
  repository: thapapath/cicd-pipeline
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: 192.168.49.2
      paths:
        - /

resources: {}
